#!/usr/bin/ruby

def tab_P (tab)
	tab = File.open("periodic_table.txt", "w") { |file|  }
end

def my_Html
	
	fileHtml = File.new("periodic_table.html", "w+")

	fileHtml.puts "<!DOCTYPE html>"
	fileHtml.puts "<html>"
	fileHtml.puts "	<head>"
	fileHtml.puts "		<meta charset=\"UTF-8\">"
	fileHtml.puts "		<link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\">"
	fileHtml.puts "		<title>periodic_table</title>"
	fileHtml.puts "	</head>"
	fileHtml.puts "	<body>"
	fileHtml.puts "		<h1>PERIODIC TABLE OF ELEMEMENTS</h1>"
	fileHtml.puts "		<div class=\"container\">"
	fileHtml.puts "		<div class=\"row\">"
	fileHtml.puts "		<br/>"
	fileHtml.puts "			<table>"
	fileHtml.puts "				<tr>"
	fileHtml.puts "					<td>"
	fileHtml.puts "						<h4>Hydrogen</h4>"
	fileHtml.puts "						<ul>"
	fileHtml.puts "							<li>No 1</li>"
	fileHtml.puts "							<li>H</li>"
	fileHtml.puts "							<li>1.00794</li>"
	fileHtml.puts "							<li>1 electron</li>"
	fileHtml.puts "						</ul>"
	fileHtml.puts "					</td>"
	fileHtml.puts "					<td class=\"ncell\"></td>"
	fileHtml.puts "					<td class=\"ncell\"></td>"
	fileHtml.puts "					<td class=\"ncell\"></td>"
	fileHtml.puts "					<td class=\"ncell\"></td>"
	fileHtml.puts "					<td class=\"ncell\"></td>"
	fileHtml.puts "					<td class=\"ncell\"></td>"
	fileHtml.puts "					<td class=\"ncell\"></td>"
	fileHtml.puts "					<td class=\"ncell\"></td>"
	fileHtml.puts "					<td class=\"ncell\"></td>"
	fileHtml.puts "					<td class=\"ncell\"></td>"
	fileHtml.puts "					<td class=\"ncell\"></td>"
	fileHtml.puts "					<td class=\"ncell\"></td>"
	fileHtml.puts "					<td class=\"ncell\"></td>"
	fileHtml.puts "					<td class=\"ncell\"></td>"
	fileHtml.puts "					<td class=\"ncell\"></td>"
	fileHtml.puts "					<td class=\"ncell\"></td>"
	fileHtml.puts "					<td>"
	fileHtml.puts "						<h4>Helium</h4>"
	fileHtml.puts "						<ul>"
	fileHtml.puts "							<li>No 1</li>"
	fileHtml.puts "							<li>H</li>"
	fileHtml.puts "							<li>1.00794</li>"
	fileHtml.puts "							<li>1 electron</li>"
	fileHtml.puts "						</ul>"
	fileHtml.puts "					</td>"
	fileHtml.puts "				</tr>"
	fileHtml.puts "				<tr>"
	fileHtml.puts "					<td>"
	fileHtml.puts ""
	fileHtml.puts ""
	fileHtml.puts ""
	fileHtml.puts ""
	fileHtml.puts ""
	fileHtml.puts ""
	fileHtml.puts ""
	fileHtml.puts "					</td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td class=\"ncell\"></td>"
	fileHtml.puts "					<td class=\"ncell\"></td>"
	fileHtml.puts "					<td class=\"ncell\"></td>"
	fileHtml.puts "					<td class=\"ncell\"></td>"
	fileHtml.puts "					<td class=\"ncell\"></td>"
	fileHtml.puts "					<td class=\"ncell\"></td>"
	fileHtml.puts "					<td class=\"ncell\"></td>"
	fileHtml.puts "					<td class=\"ncell\"></td>"
	fileHtml.puts "					<td class=\"ncell\"></td>"
	fileHtml.puts "					<td class=\"ncell\"></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "				</tr>"
	fileHtml.puts "				<tr>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td class=\"ncell\"></td>"
	fileHtml.puts "					<td class=\"ncell\"></td>"
	fileHtml.puts "					<td class=\"ncell\"></td>"
	fileHtml.puts "					<td class=\"ncell\"></td>"
	fileHtml.puts "					<td class=\"ncell\"></td>"
	fileHtml.puts "					<td class=\"ncell\"></td>"
	fileHtml.puts "					<td class=\"ncell\"></td>"
	fileHtml.puts "					<td class=\"ncell\"></td>"
	fileHtml.puts "					<td class=\"ncell\"></td>"
	fileHtml.puts "					<td class=\"ncell\"></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "				</tr>"
	fileHtml.puts "				<tr>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "				</tr>"
	fileHtml.puts "				<tr>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "				</tr>"
	fileHtml.puts "				<tr>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "				</tr>"
	fileHtml.puts "				<tr>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "					<td></td>"
	fileHtml.puts "				</tr>"
	fileHtml.puts "			</table>"
	fileHtml.puts "		</div>"
	fileHtml.puts "		</div>"
	fileHtml.puts "	</body>"
	fileHtml.puts "</html>"


	fileHtml.close()
end

my_Html

